### ISSUE TITLE
VUNIT returns an invalid value

### ISSUE THREAD

**Issue by gingeralesy** [Shinmera/3d-vectors#1]
The functions VUNIT and NVUNIT calculate a vector relative to the length of the vector. This causes the magnitude of the produced vector to be more than one.

This should be fixed by calculating the vector relative to its magnitude.

https://en.wikipedia.org/wiki/Unit_vector

https://github.com/Shinmera/3d-vectors/blob/master/ops.lisp#L315-L323

**Comment by Shinmera** [comment]
What do you mean by a vector's "magnitude"?

**Comment by gingeralesy** [comment]
The sum of the absolute dimensional values of a vector.

(VEC 1 2 3) would have a magnitude of 6. Thus its unit vector would be (VEC (/ 1 6) (/ 2 6) (/ 3 6)) with a magnitude of 1.

**Comment by gingeralesy** [comment]
Wait, hold on. My brain just did a dumb there. Yes, the VUNIT is returning the correct values.

**Comment by Shinmera** [comment]
Well, I mean, normalisation of a vector is always relative to a norm. If the norm is the 2-norm, like it is usually, then what  we do here is correct. If the norm were something else like the 1-norm, or the maximum-norm, then obviously you'd need to divide by something else.

**Comment by Shinmera** [comment]
To take a positive out of this, I added some more norm functions in 1adf840
