### ISSUE TITLE
asdf:test-system fails because of missing "parachute" component

### ISSUE THREAD

**Issue by mirkov** [Shinmera/3d-vectors#11]
Running `asdf:test-system` results in 
```
; Evaluation aborted on Component :PARACHUTE not found, required by #<SYSTEM "3d-vectors-test">.
```
The simple workaround is to load "parachute" before running the tests.
All tests pass.

**Comment by Shinmera** [comment]
Actually this looks like an error with your own configuration. ASDF is not like quicklisp, and will not pull in missing dependencies. It's on you to ensure all required systems are present.

**Comment by mirkov** [comment]
My workflow, as best I remember it, was to first quickload the system, and then run the test.

I assumed that when I quickload a system, the testing components will also get loaded. I can see that some users may not want to download all the testing components along with the system.
